package com.aitrack.server.infrastructure.config;

import org.junit.jupiter.api.Test;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.sql.Connection;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

class EditRecordSchemaMigratorTest {

    @Test
    void addsPromptSummaryColumnToExistingEditRecordsTable() throws Exception {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
            "jdbc:h2:mem:edit_record_migration;DB_CLOSE_DELAY=-1;MODE=PostgreSQL",
            "sa",
            ""
        );
        dataSource.setDriverClassName("org.h2.Driver");
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("""
                CREATE TABLE edit_records (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  token_key VARCHAR(16) NOT NULL,
                  device_id VARCHAR(64) NOT NULL,
                  hostname VARCHAR(255),
                  tool VARCHAR(64) NOT NULL,
                  provider VARCHAR(64) NOT NULL,
                  session_id VARCHAR(128) NOT NULL,
                  repo_url VARCHAR(512) NOT NULL,
                  branch VARCHAR(128) NOT NULL,
                  current_sha VARCHAR(128) NOT NULL,
                  file_path VARCHAR(1024) NOT NULL,
                  added_lines BIGINT NOT NULL,
                  removed_lines BIGINT NOT NULL,
                  diff_hunk TEXT,
                  metadata TEXT,
                  timestamp VARCHAR(64) NOT NULL,
                  record_sig VARCHAR(64) NOT NULL,
                  status VARCHAR(16) NOT NULL,
                  received_at TIMESTAMP NOT NULL
                )
                """);
        }

        EditRecordSchemaMigrator migrator = new EditRecordSchemaMigrator(dataSource);
        migrator.migrate();
        migrator.migrate();

        try (Connection connection = dataSource.getConnection();
             var columns = connection.getMetaData().getColumns(null, null, "EDIT_RECORDS", "PROMPT_SUMMARY")) {
            assertThat(columns.next()).isTrue();
            assertThat(columns.getString("TYPE_NAME").toUpperCase()).contains("CHAR");
        }
    }

    @Test
    void postgresMigrationSqlMentionsPromptSummary() {
        String ddl = String.join("\n", EditRecordSchemaMigrator.postgresMigrationSql());

        assertThat(ddl).contains("edit_records", "prompt_summary", "TEXT");
    }
}
