package com.aitrack.server.infrastructure.config;

import org.junit.jupiter.api.Test;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

class UsageDailyRollupSchemaMigratorTest {

    @Test
    void migratesOldSixColumnUniqueSoUsageBasisRowsCanCoexist() throws Exception {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
            "jdbc:h2:mem:rollup_migration;DB_CLOSE_DELAY=-1;MODE=PostgreSQL",
            "sa",
            ""
        );
        dataSource.setDriverClassName("org.h2.Driver");
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("""
                CREATE TABLE usage_daily_rollups (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  token_key VARCHAR(32) NOT NULL,
                  device_id VARCHAR(64) NOT NULL,
                  "day" VARCHAR(10) NOT NULL,
                  agent VARCHAR(64) NOT NULL,
                  model VARCHAR(255) NOT NULL,
                  account VARCHAR(255) NOT NULL DEFAULT '',
                  tokens_in BIGINT NOT NULL DEFAULT 0,
                  tokens_out BIGINT NOT NULL DEFAULT 0,
                  tokens_cache_read BIGINT NOT NULL DEFAULT 0,
                  tokens_cache_write BIGINT NOT NULL DEFAULT 0,
                  tokens_reasoning BIGINT NOT NULL DEFAULT 0,
                  message_count BIGINT NOT NULL DEFAULT 0,
                  source_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
                  updated_at TIMESTAMP NOT NULL,
                  CONSTRAINT uk_usage_daily_rollup UNIQUE(token_key, device_id, "day", agent, model, account)
                )
                """);
        }

        UsageDailyRollupSchemaMigrator migrator = new UsageDailyRollupSchemaMigrator(dataSource);
        migrator.migrate();
        migrator.migrate();

        insertRollup(dataSource, "native");
        insertRollup(dataSource, "local_derived");

        try (Connection connection = dataSource.getConnection();
             var rs = connection.getMetaData().getIndexInfo(null, null, "USAGE_DAILY_ROLLUPS", true, false)) {
            boolean hasUsageBasisUnique = false;
            while (rs.next()) {
                String indexName = rs.getString("INDEX_NAME");
                String columnName = rs.getString("COLUMN_NAME");
                if ("UK_USAGE_DAILY_ROLLUPS_BASIS".equals(indexName) && "USAGE_BASIS".equals(columnName)) {
                    hasUsageBasisUnique = true;
                }
            }
            assertThat(hasUsageBasisUnique).isTrue();
        }
    }

    @Test
    void migrationSqlMentionsLegacyUniqueNamesAndSevenColumnUnique() {
        String ddl = String.join("\n", UsageDailyRollupSchemaMigrator.postgresMigrationSql());

        assertThat(ddl).contains(
            "usage_daily_rollups_token_key_device_id_day_agent_model_account_key",
            "usage_daily_rollups_token_key_device_id_day_agent_model_acc_key",
            "uk_usage_daily_rollup",
            "token_key, device_id, day, agent, model, account, usage_basis"
        );
    }

    private static void insertRollup(DriverManagerDataSource dataSource, String usageBasis) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             var statement = connection.prepareStatement("""
                 INSERT INTO usage_daily_rollups (
                   token_key, device_id, "day", agent, model, account, usage_basis, updated_at
                 ) VALUES ('token', 'device', '2026-06-30', 'codex', 'gpt-5', '', ?, CURRENT_TIMESTAMP)
                 """)) {
            statement.setString(1, usageBasis);
            statement.executeUpdate();
        }
    }
}
